/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.Profile;

/**
 *
 * @author Алёшечка
 */
public class AdminWindow extends javax.swing.JFrame {
    private Profile profile;
    /**
     * Creates new form AdminWindow
     */
    public AdminWindow(Profile profile) {
        initComponents();
        this.profile = profile;
        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension d = tool.getScreenSize();
        this.setBounds(0, 0, d.width, d.height);
        
        ActionListener addEmployeeListener = new AddEmployeeListener();        
        jMenuItem3.addActionListener(addEmployeeListener);
        jButton1.addActionListener(addEmployeeListener);
        ActionListener showEmployeeListener = new ShowEmployeeListener();
        jMenuItem4.addActionListener(showEmployeeListener);
        jButton2.addActionListener(showEmployeeListener);
        
        jButton3.addActionListener((ActionEvent s) -> {
            if (StatisticsWindow.getCount() == 0) {
                StatisticsWindow statisticsWindowInternalFrame = new StatisticsWindow();
                statisticsWindowInternalFrame.setBounds(50, 50, 420, 300);
                jDesktopPane1.add(statisticsWindowInternalFrame);
                statisticsWindowInternalFrame.setVisible(true);
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("addEmployee");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setText("ShowEmploee");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText("Statistics");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Employee");

        jMenuItem3.setText("AddEmployee");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("ShowEmployee");
        jMenu2.add(jMenuItem4);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    /**
     * @param args the command line arguments
     */
    
   
    private class AddEmployeeListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (AddEmployee.getCount() == 0) {
                AddEmployee addEmployeeInternalFrame = new AddEmployee();
                addEmployeeInternalFrame.setBounds(50, 50, 400, 300);
                jDesktopPane1.add(addEmployeeInternalFrame);
                addEmployeeInternalFrame.setVisible(true);
            }
        }
    }
    
    private class ShowEmployeeListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (ShowEmployee.getCount() == 0) {
                ShowEmployee showEmployeeInternalFrame = new ShowEmployee();
                showEmployeeInternalFrame.setBounds(75, 75, 400, 300);
                jDesktopPane1.add(showEmployeeInternalFrame);
                showEmployeeInternalFrame.setVisible(true);
            }
        }
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
